<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RunVersion>8</RunVersion>
    <UseX>0</UseX>
    <DefineConstants Condition="'$(UseX)'=='1'">USEX</DefineConstants>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(RunVersion)'=='8'">net8.0</TargetFramework>
    <TargetFramework Condition="'$(RunVersion)'=='9'">net9.0</TargetFramework>
    <TargetFramework Condition="'$(RunVersion)'=='10'">net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(RunVersion)'=='8'">
    <PackageReference Condition="'$(UseX)'=='0'" Include="EntityFrameworkCore.DataEncryption" VersionOverride="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" VersionOverride="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" VersionOverride="8.0.22" />
  </ItemGroup>

  <ItemGroup Condition="'$(RunVersion)'=='9'">
    <PackageReference Condition="'$(UseX)'=='0'" Include="EntityFrameworkCore.DataEncryption" VersionOverride="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" VersionOverride="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" VersionOverride="9.0.11" />
  </ItemGroup>

  <ItemGroup Condition="'$(RunVersion)'=='10'">
    <PackageReference Condition="'$(UseX)'=='0'" Include="EntityFrameworkCore.DataEncryption" VersionOverride="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" VersionOverride="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" VersionOverride="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Condition="'$(UseX)'=='1'" Include="..\..\src\X.EntityFrameworkCore.FieldEncryption\X.EntityFrameworkCore.FieldEncryption.csproj" />
  </ItemGroup>

</Project>
