<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\configureawait.props" />
  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFramework)</TargetFrameworks>
    <RootNamespace>X.Bff</RootNamespace>
    <PackageId>X.Bff</PackageId>
    <Description>Backend for Frontend</Description>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Duende.AccessTokenManagement.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
</Project>
