<Project>
  <PropertyGroup>
    <DefaultTargetFramework>net8.0;net9.0;net10.0</DefaultTargetFramework>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)X.ruleset</CodeAnalysisRuleSet>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
  </ItemGroup>
</Project>
