name: "Pack and push package with nexus"

on:
    workflow_dispatch:
        inputs:
            packageVersion:
                description: "Package Version"
                required: true
                type: string

env:
    NUGET_REGISTRY: http://220.165.143.67:8081/repository/nuget-hosted/

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Echo build and push config info
              run: |
                  echo "Nuget registry: $Nuget_Registry"
                  echo "Package version: $Package_Version"
              env:
                  Nuget_Registry: ${{ env.NUGET_REGISTRY }}
                  Package_Version: ${{ inputs.packageVersion }}
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup .NET 9.x
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.x'
            - name: Display dotnet version
              run: dotnet --version
            - name: Build with dotnet
              run: dotnet build --configuration Release -p:Version=${{ inputs.packageVersion }}
            - name: Create Nuget Packages
              uses: EasyDesk/action-dotnet-pack@v1.0.3
              with:
                  project-names: |
                      src/X.Captcha
                      src/X.EntityFrameworkCore.FieldEncryption
                      src/X.Swashbuckle
                  # NuGet Package Version
                  package-version: ${{ inputs.packageVersion }}
                  output-dir: "./nupkg"
            - name: Push Nuget Packages
              uses: EasyDesk/action-nuget-push@v1.0.0
              with:
                  nuget-url: ${{ env.NUGET_REGISTRY }}
                  # The Nuget API key.
                  nuget-api-key: ${{ secrets.NexusNugetKey }}
                  publish-dir: "./nupkg"
